# -*- coding: utf-8 -*-
"""Rithika-numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZBbGt35RaVN2KlOCpiQqcdZGONRrwsu

11/09/2023(MON)
P.Rithika Reddy

**20221BCA0318**
"""

!python --version

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

x=3
print(x,type(x))

x='c'
print(x,type(x))

"""**27/09/2023(wed)**

**lab2**
"""

L=[1,2,3]
it=iter(L)
it

A=[1,2,3]
a=iter(A)
a

type(L)

next(it)

it._next_()

for i in iter(L):
  print(i)

for i in L:
  print(i)

L=[1,2,3]
iterator=iter(L)
t=tuple(iterator)
type(t)

L=[1,2,3]
iterator=iter(L)
a,b=iterator
a,b

m={'Jan' : 1, 'Feb' : 2, 'Mar' : 3,'Apr' : 4,'May' : 5,'Jun' : 6,'Jul' : 7,'Aug' : 8,'Sep' : 9,'Oct' : 10,'Nov' : 11,'Dec' : 12}
for key in m:
  print(key,m[key])

l=[1,2,3]
[2*i for i in l]

l=[1,2,3]
for i in l:
  x=2*i
  print(x)

L=[('Italy', 'Rome'),('France','Paris'),('US','Washington DC')]
dict(iter(L))

type(L)

t=dict(iter(L))
type(t)

line_list=[' Presidency University\n', ' Computer Science Department\n', ' Dept Of CSE \n', ' \n']
stripped_iter=(line.strip() for line in line_list)
stripped_iter

print(stripped_iter)

line_list=[' Presidency University\n', ' Computer Science Department\n', ' Dept Of CSE \n', ' \n']
stripped_list=(line.strip() for line in line_list)
print(stripped_list)

stripped_list=(line.strip() for line in line_list if line !=" ")
print(stripped_list)